website/views.py
from flask import Blueprint, render_template, request, redirect, url_for, flash, session
from flask_login import login_required, current_user
from website.models import Product


views = Blueprint('views', __name__)
categ = "Всі меблі"

@views.route('/', methods=['GET', 'POST'])
def home():
    if categ == "Всі меблі":
        products = Product.query.all()
    else:
        products = Product.query.filter_by(category=categ).all()

    if request.method == 'POST':
        product_id = int(request.form.get('add-to-cart'))
        product = next((p for p in products if p.id == product_id), None)

        if product:
            cart = session.get('cart', [])
            for item in cart:
                if product_id == item.get('id'):
                    if item['cnt'] < item['quantity']:  # Перевірка, чи кількість товару не перевищує quantity
                        item['cnt'] = item.get('cnt', 0) + 1
                        flash(f'{product.description} додано в корзину', 'success')
                    else:
                        flash('Максимальна кількість досягнута для цього товару', 'error')
                    break
            else:
                cart.append({'cnt': 1, **product.to_dict()})
                session['cart'] = cart
                flash(f'{product.description} додано в корзину', 'success')
        else:
            flash('Товар не знайдено', 'error')

    cart = session.get('cart', [])

    return render_template("home.html", user=current_user, products=products, categ = categ, cart=cart)

@views.route('/update_category', methods=['POST'])
def update_category():
    global categ
    categ = request.form.get('category', categ)
    return redirect(url_for('views.home'))


@views.route('/remove_from_cart/<int:product_id>', methods=['POST'])
def remove_from_cart(product_id):
    if 'cart' in session:
        cart = session['cart']

        for item in cart:
            if item.get('id') == product_id:
                item['cnt'] = max(0, item.get('cnt', 0) - 1)

                if item['cnt'] == 0:
                    cart.remove(item)

                session['cart'] = cart
                flash('Товар видалено з корзини', 'success')
                break
    else:
        flash('Корзина пуста', 'error')

    return redirect(url_for('views.home'))

website/templates/about_us.html
{% extends  "base.html" %} {% block title %}Про нас{% endblock %}

{% block content %}
<form method="POST">
<div class="container">
    <section class="main-content">
        <h2>Про нас</h2>
        <p>
            Ласкаво просимо до нашого магазину меблів! Ми пропонуємо широкий вибір високоякісних меблів для вашого дому.
        </p>
        <p>
            Наша місія - надавати клієнтам тільки найкращі меблі з урахуванням сучасних тенденцій та ваших унікальних потреб.
        </p>
        <p>
            Запрошуємо вас відвідати наш магазин і знайти ідеальні меблі для вашого простору.
        </p>
    </section>
    </div>
</form>
{% endblock %}

{% block extra_css %}
    <!-- Підключення вашого CSS файлу -->
    <link rel="stylesheet" type="text/css" href="/website/static/about_us.css">
{% endblock %}

website/templates/base.html
<!DOCTYPE html>
<html lang="ua">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous"/>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u"
          crossorigin="anonymous"/>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
      crossorigin="anonymous"/>

    <link rel="stylesheet" type="text/css" href="/website/static/styles.css">

    <title>{% block title %}Home{% endblock %}</title>
    {% block extra_css %}{% endblock %}


</head>
<body>

<header>
    <h1>Магазин меблів</h1>

    <div class="action-bar">
   <div class="catalog-dropdown">
    <form method="POST" action="{{ url_for('views.update_category') }}">
        <div class="dropdown">
            <button class="btn btn-secondary dropdown-toggle" type="button" id="catalogDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Виберіть каталог
            </button>
            <ul class="dropdown-menu" aria-labelledby="catalogDropdown">
                <li><button type="submit" class="dropdown-item" name="category" value="Всі меблі">Всі меблі</button></li>
                <li><button type="submit" class="dropdown-item" name="category" value="Кухня">Кухня</button></li>
                <li><button type="submit" class="dropdown-item" name="category" value="Вітальня">Вітальня</button></li>
                <li><button type="submit" class="dropdown-item" name="category" value="Спальня">Спальня</button></li>
                <li><button type="submit" class="dropdown-item" name="category" value="Дитяча">Дитяча</button></li>
            </ul>
        </div>
    </form>
</div>
<nav>
        <div class="navbar-wrap">
        <ul>
            <li><a id="home" href="/">Головна</a></li>
            <li><a id="about-us" href="/about-us">Про нас</a></li>
            <li><a id="contact" href="/contact">Контакти</a></li>
            {% if user.is_authenticated %}
            <li><a id="logout" href="/logout">Вийти з акаунту</a></li>
            {% else %}
            <li><a id="sign-up" href="/sign-up">Реєстрація</a></li>
            <li><a id="login" href="/login">Вхід</a></li>
            {% endif %}
        </ul>
            {% if user.is_authenticated %}
            <a href="#modalWin" class="callback">Передзвоніть мені</a>
            {% else %}
            <a href="/login" class="callback">Передзвоніть мені</a>
            {% endif %}
        </div>
    </nav>

    <div class="cart">
            {% if user.is_authenticated %}
            <a href="#" data-toggle="modal" data-target="#cartModal">
                <ion-icon name="cart-outline"></ion-icon></a>
            {% else %}
            <a href="/login" data-toggle="modal">
            <ion-icon name="cart-outline"></ion-icon></a>
            {% endif %}
    </div>
</div>
</header>


    {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
            {% for category, message in messages %}
                <div class="alert alert-dismissible {% if category == 'error' %}alert-danger{% else %}alert-success{% endif %}">
                    <button type="button" class="close" data-dismiss="alert">&times;</button>
                    {{ message }}
                </div>
            {% endfor %}
        {% endif %}
    {% endwith %}



<div id="modalWin" class="modal">
    <div class="modal-window">
        <h1>Очікуйте. Менеджер зараз з вами зв'яжеться</h1>
        <a href="/" class="btn-close">X</a>
    </div>
    <div class="overlay"></div>
</div>

  <!-- Cart modal -->
  <div class="modal fade" id="cartModal" tabindex="-1" role="dialog" aria-labelledby="cartModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="cartModalLabel">Корзина</h5>
            </div>
            <div class="modal-body">
                <table class="table">
                    <thead>
                        <tr>
                            <th scope="col">Товар</th>
                            <th scope="col">Ціна</th>
                            <th scope="col">Кількість</th>
                            <th scope="col">Дія</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for item in cart %}
                            <tr>
                                <td>{{ item.description }}</td>
                                <td>{{ item.price }}₴</td>
                                <td>{{ item.cnt }}</td>
                                <td>
                                    <form method="post" action="{{ url_for('views.remove_from_cart', product_id=item['id']) }}">
                                        <input type="hidden" name="_method" value="DELETE">
                                        <button type="submit" class="btn btn-danger">Видалити</button>
                                    </form>
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Продовжити покупки</button>
                {% if cart %}
                <a href="#" class="btn btn-primary checkout-btn" onclick="showModal()">Перейти до оформлення замовлення</a>
                {% else %}
                <p>Кошик порожній</p>
                {% endif %}
            </div>
        </div>
    </div>
</div>


<div class="container"> {% block content%} {% endblock %}</div>

<footer>
    <p>&copy; 2023 Магазин меблів. Усі права захищені.</p>
</footer>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>

    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
            integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
            crossorigin="anonymous"></script>

    <script src="https://unpkg.com/ionicons@5.4.0/dist/ionicons.js"></script>

<div id="modalWin2" class="modal" style="display: none;">
    <div class="modal-window">
        <h1>Очікуйте. Менеджер зараз з вами зв'яжеться для подальшого оформлення замовлення</h1>
        <a href="/" class="btn-close">X</a>
    </div>
    <div class="overlay3"></div>
</div>

<script>
    function showModal() {
        document.getElementById('modalWin2').classList.add('show');
    }
</script>

</body>
</html>

website/templates/contact.html
{% extends  "base.html" %} {% block title %}Контакти{% endblock %}

{% block content %}
<form method="POST">
<div class="container">
    <section class="main-content">
        <h2>Зв'яжіться з нами</h2>
        <p>
            Маєте запитання чи побажання? Ми будемо раді почути вас! Зв'яжіться з нами, використовуючи контактну інформацію нижче.
        </p>

        <address>
            <strong>Адреса нашого магазину:</strong><br>
            Україна, Львів, вул. Степана Бандери
        </address>

        <p>
            <strong>Електронна пошта:</strong> info@example.com<br>
            <strong>Номер телефону:</strong> +1 (123) 456-7890
        </p>
    </section>
</div>
</form>
{% endblock %}

{% block extra_css %}
    <!-- Підключення вашого CSS файлу -->
    <link rel="stylesheet" type="text/css" href="/website/static/contact.css">
{% endblock %}

website/templates/home.html
{% extends  "base.html" %} {% block title %}Головна{% endblock %}

{% block content %}
<h1>{{ categ }}</h1>
<form method="POST">
    <div class="container">
        <div class="row">
            {% for product in products %}
                <div class="col-md-3">
                    <div class="product">
                        <div class="image">
                            <a href="{{ url_for('info.product', product_id=product.id) }}">
                            <img src={{ product.path_to_img }} alt={{ product.description }} >
                                </a>
                            <div class="placeholder"></div>
                            <div class="info">
                                <h3>{{ product.description }}</h3>
                                <div class="info-price">
                                    <span class="price">{{ product.price }}₴</span>
                                    {% if user.is_authenticated %}
                                    <button class="add-to-cart" name="add-to-cart" value={{ product.id }}>
                                        <ion-icon name="cart-outline"></ion-icon>
                                     </button>
                                    {% else %}
                                     <a href="/login" class="add-to-cart">
                                      <ion-icon name="cart-outline"></ion-icon>
                                    </a>
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
</form>

{% endblock %}



{% block extra_css %}
    <link rel="stylesheet" type="text/css" href="/website/static/home.css">
{% endblock %}

website/templates/login.html
{% extends  "base.html" %} {% block title %}Вхід{% endblock %}

{% block content %}
<form method="POST">
  <h3 align="center">Вхід</h3>
  <div class="form-group">
    <label for="email">Електронна пошта</label>
    <input
      type="email"
      class="form-control"
      id="email"
      name="email"
      placeholder="Введіть електронну пошту"
    />
  </div>
  <div class="form-group">
    <label for="password">Пароль</label>
    <input
      type="password"
      class="form-control"
      id="password"
      name="password"
      placeholder="Введіть пароль"
    />
  </div>
  <br />
  <button type="submit" class="btn btn-primary">Login</button>
</form>
{% endblock %}

website/templates/product.html
{% extends  "base.html" %} {% block title %}Товар{% endblock %}

{% block content %}
<div class="product-container">

    <div class="product-photo">
        <img src={{ product.path_to_img }} alt="{{ product.description }}" width="300">
    </div>

    <div class="product-details">
        <h2  class="ph2">{{ product.description }}</h2>

        <!-- Product Characteristics -->
        <ul class="list2">
            <li>Колір: {{ product.color }}</li>
            <li>Матеріал: {{ product.material }}</li>
            <li>Ціна: ₴{{ product.price }}</li>
            <li>Висота: {{ product.height }} см.</li>
            <li>Ширина: {{ product.width }} см.</li>
            <li>Довжина: {{ product.length }} см.</li>
            <li>Кількість: {{ product.quantity }}</li>
        </ul>

          <form method="post" action="{% if user.is_authenticated %}{{ url_for('views.home') }}{% else %}{{ url_for('auth.login') }}{% endif %}">
    <button type="submit" class="add-to-cart" name="add-to-cart" value="{{ product.id }}">
        Додати до корзини
    </button>
</form>

    </div>
</div>
{% endblock %}

        {% block extra_css %}
    <link rel="stylesheet" type="text/css" href="/website/static/product.css"/>
        {% endblock %}


website/templates/sign_up.html
{% extends  "base.html" %} {% block title %}Реєстрація{% endblock %}

{% block content %}
<form method="POST">
    <h3 align="center">Реєстрація</h3>
    <div class="form-group">
        <label for="email">Електронна пошта</label>
        <input
                type="email"
                class="form-control"
                id="email"
                name="email"
                placeholder="Введіть електронну пошту"
        />
    </div>
    <div class="form-group">
        <label for="firstName">Ім'я</label>
        <input
                type="text"
                class="form-control"
                id="firstName"
                name="firstName"
                placeholder="Введіть ім'я"
        />
    </div>
    <div class="form-group">
        <label for="surName">Прізвище</label>
        <input
                type="text"
                class="form-control"
                id="surName"
                name="surName"
                placeholder="Введіть прізвище"
        />
    </div>
    <div class="form-group">
        <label for="usercontact">Номер телефону</label>
        <input
                type="text"
                class="form-control"
                id="usercontact"
                name="usercontact"
                placeholder="Введіть номер телефону"
        />
    </div>
    <div class="form-group">
        <label for="password1">Пароль</label>
        <input
                type="password"
                class="form-control"
                id="password1"
                name="password1"
                placeholder="Введіть пароль"
        />
    </div>
    <div class="form-group">
        <label for="password2">Пароль (підтвердження)</label>
        <input
                type="password"
                class="form-control"
                id="password2"
                name="password2"
                placeholder="Підтвердіть пароль"
        />
    </div>
    <br />
    <button type="submit" class="btn btn-primary">Submit</button>
</form>
{% endblock %}